In [1]:
import torch

In [2]:
x = torch.tensor(3.0)
y = torch.tensor(2.0)

x+y, x*y, x/y, x**y

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

In [5]:
x = torch.arange(3)
x

tensor([0, 1, 2])

In [6]:
x.shape

torch.Size([3])

In [8]:
A = torch.arange(6).reshape(3,2)
A

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [9]:
A.T

tensor([[0, 2, 4],
        [1, 3, 5]])

Symmetric matrices are equal to their transposes

In [10]:
A = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
A == A.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [11]:
torch.arange(24).reshape(2, 3, 4)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [12]:
A = torch.arange(6, dtype=torch.float32).reshape(2, 3)
B = A.clone()  # Assign a copy of A to B by allocating new memory
A, A + B

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[ 0.,  2.,  4.],
         [ 6.,  8., 10.]]))

Hadamard product for elementwise product

In [13]:
A * B

tensor([[ 0.,  1.,  4.],
        [ 9., 16., 25.]])

In [14]:
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a + X, (a * X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

Reduction to calculate sum of tensor's elements. By defaut does by row and column to get scalar, else can specifiy row reduction with 0 or col reduction with 1.

In [20]:
x = torch.arange(3, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2.]), tensor(3.))

In [21]:
A

tensor([[0., 1., 2.],
        [3., 4., 5.]])

In [16]:
A.shape, A.sum()

(torch.Size([2, 3]), tensor(15.))

In [22]:
A.shape, A.sum(axis=0), A.sum(axis=0).shape

(torch.Size([2, 3]), tensor([3., 5., 7.]), torch.Size([3]))

In [23]:
A.shape, A.sum(axis=1), A.sum(axis=1).shape

(torch.Size([2, 3]), tensor([ 3., 12.]), torch.Size([2]))

In [24]:
A.sum(axis=[0, 1]) == A.sum()  # Same as A.sum()

tensor(True)

In [25]:
A.mean(), A.sum() / A.numel()

(tensor(2.5000), tensor(2.5000))

In [27]:
A

tensor([[0., 1., 2.],
        [3., 4., 5.]])

In [26]:
A.mean(axis=0), A.sum(axis=0) / A.shape[0]

(tensor([1.5000, 2.5000, 3.5000]), tensor([1.5000, 2.5000, 3.5000]))

Non-reducing sum to leave axes unchanged when mapping a function (broadcasts instead)

In [29]:
sum_A = A.sum(axis=1, keepdims=True)
sum_A, sum_A.shape

(tensor([[ 3.],
         [12.]]),
 torch.Size([2, 1]))

In [32]:
A / sum_A # broadcasting to create matrix where e/ row sums to 1

tensor([[0.0000, 0.3333, 0.6667],
        [0.2500, 0.3333, 0.4167]])

Dot product ops

In [33]:
y = torch.ones(3, dtype = torch.float32)
x, y, torch.dot(x, y) # or torch.sum(x * y)

(tensor([0., 1., 2.]), tensor([1., 1., 1.]), tensor(3.))

Matrix mult

In [36]:
A

tensor([[0., 1., 2.],
        [3., 4., 5.]])

In [34]:
A.shape, x.shape, torch.mv(A, x), A@x

(torch.Size([2, 3]), torch.Size([3]), tensor([ 5., 14.]), tensor([ 5., 14.]))

In [35]:
B = torch.ones(3, 4)
torch.mm(A, B), A@B

(tensor([[ 3.,  3.,  3.,  3.],
         [12., 12., 12., 12.]]),
 tensor([[ 3.,  3.,  3.,  3.],
         [12., 12., 12., 12.]]))

Norms

In [40]:
u = torch.tensor([3.0, -4.0])
torch.norm(u) # l2 norm

tensor(5.)

In [41]:
torch.abs(u).sum() # l1 norm

tensor(7.)

Frobenius Norm -- square root of the sum of squares (the l2 norm)

In [42]:
torch.norm(torch.ones((4, 9)))

tensor(6.)